### ISSUE TITLE
REQUEST_URI support

### ISSUE THREAD

**Issue by fabianx-ai** [beberlei/hhvm-serve#1]
Hi,

Thanks to this fantastic project I finally got hhvm and PHP 5.3 back working in no sudo mode on travis-ci for https://github.com/LionsAd/drupal_ti.

Could we please in addition to PATH_INFO also add REQUEST_URI, which is PATH_INFO + QUERY_ARGS?

I don't know any go, so asking as a feature request.

Thanks,

Fabian

**Comment by beberlei** [comment]
Fixed
