### ISSUE TITLE
Testsuite for hhvm-serve

### ISSUE THREAD

**Issue by Naktibalda** [beberlei/hhvm-serve#3]
Hi,

I started a new project https://github.com/Naktibalda/hhvm-serve-tests to demonstrate differences between php built-in server and hhvm-serve.

Here are results of the first builds: https://travis-ci.org/Naktibalda/hhvm-serve-tests/branches

**Comment by beberlei** [comment]
This might be due to missing REQUEST_URI support, which will be in #2

**Comment by beberlei** [comment]
Added `REQUEST_URI` support.
